# Generated by Django 3.2.7 on 2021-09-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contrac',
            new_name='contractForm',
        ),
    ]
